name: CI/CD

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Docker Compose 설치
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Docker Compose 버전 확인
      - name: Check Docker Compose version
        run: docker-compose --version

      # main/resources에 기본 프로퍼티 파일 생성
      - run: |
          mkdir -p ./src/main/resources
          touch ./src/main/resources/application.properties  # 파일 생성
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties  # 파일에 내용 추가

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      # gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean bootJar -x test

      # 현재 시간 정보 가져오기
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      # 빌드된 JAR 파일 경로 설정
      - name: Set artifact path
        run: |
          artifact=$(ls ./build/libs/WEB1_2_BUMBLEBEE_BE-*.jar | head -n 1)
          artifact=${artifact//\"/}  # Remove any double quotes from the artifact path
          echo "artifact=$artifact" >> $GITHUB_ENV

      # EC2 SSH 키를 파일로 저장
      - name: Save SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ssh-key.pem
          chmod 600 /tmp/ssh-key.pem

      # EC2에서 Docker 디렉토리 권한 설정 (파일 복사 전)
      - name: Set Docker directory permissions on EC2
        run: |
          ssh -i /tmp/ssh-key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo mkdir -p /Docker"
          ssh -i /tmp/ssh-key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo chown -R ec2-user:ec2-user /Docker"
          ssh -i /tmp/ssh-key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo chmod -R 777 /Docker"

      # EC2에 파일 복사 (docker-compose.yml과 python-server 디렉토리)
      - name: Copy docker-compose.yml and python-server to EC2
        run: |
          # docker-compose.yml 파일 복사
          scp -i /tmp/ssh-key.pem -o StrictHostKeyChecking=no ./docker-compose.yml ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/Docker/
          
          # python-server 디렉토리 복사 (-r 옵션을 사용하여 디렉토리 복사)
          scp -i /tmp/ssh-key.pem -o StrictHostKeyChecking=no -r ./python-server ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/Docker/

      # Elastic Beanstalk 배포
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: bumblebee-final
          environment_name: Bumblebee-final-env
          version_label: github-action-${{ steps.current-time.outputs.formattedTime }}
          region: ap-northeast-2
          deployment_package: ${{ env.artifact }}  # JAR 파일 경로를 환경 변수로 전달